### PR TITLE
use 1.0.0 as the default version

### PR DESCRIPTION
**Pull request by sergioramos**
follows the default of npm3 init

### CODE REVIEW

**Comment by mmun** [comment]
:+1:

**Comment by dignifiedquire** [comment]
:+1:

**Comment by dherman** [comment]
Huh. I was totally surprised to hear this until I learned [a bit of the history](https://github.com/dominictarr/semver-ftw/issues/2) of how people have tried to deprecate or eschew the 0.x rules of semver. Personally, I'm a strong proponent myself of semver's semantics for 0.x. When I create new projects, they're at 0.x until they reach a point of strong backwards-compatibility guarantees. (See neon, for example!) So changing this default would just make it always wrong for me. Also note that `cargo new` starts a project at 0.1.0.

That said, it's true that `neon new` is for creating a Node package; the Rust crate is an internal implementation artifact. So that argues for breaking the tie between npm and cargo in favor of npm.

Is it really true that everyone starts their npm packages at 1.0.0? Sure, the tooling tries to force that on you, but most of the packages I ever see are at 0.x. It seems pretty unlikely to me that tooling defaults can eliminate the strong signalling that 0.x vs 1.x provides.

**Comment by mmun** [comment]
Changed my mind. Long live 0.x. :crown:

**Comment by dherman** [comment]
Not seeing more discussion, so I'll leave it at 0.1.0 for now.

**Comment by sergioramos** [comment]
Some people explain better than me why it is important to use 1.0: http://jeremyckahn.github.io/blog/2013/12/29/the-fear-of-1-dot-0-0/

**Comment by domenic** [comment]
For me, the first version I commit to source control is 1.0.0-pre, and the first version I publish to npm is 1.0.0. If it's not stable enough to get 1.0.0, it doesn't deserve to be published to npm; if it's published to npm, any consumers deserve to get the benefits of bugfixes instead of being forced to stick to an exact version like they would if I published it as 0.x.

**Pull request closed without merging**
