### PR TITLE
Add parameter to override Node module ABI version

### PR DESCRIPTION
**Pull request by EdShaw**
Set NEON_NODE_ABI iff the caller specifies a Node module ABI version; else, neon will base it on the constant in the node headers.

Related:
https://github.com/rustbridge/neon/pull/109

### CODE REVIEW

**Comment by emk** [comment]
Please let me know if there's anything I can do to help test this change. Issues with the ABI version are making it difficult for me to get an Electron app up and running on the Mac, and I'd be happy to test things for use with Electron.

**Comment by EdShaw** [comment]
It's be helpful to see that it's working on someone else's system. ;) This should get you up and running with neon+electron (it's what motivated me).

In your neon module, if you point your npm package to depend on this branch, and your cargo project to the corresponding neon branch, it should work with electron-rebuild.

I did have issues with electron-rebuild and rustup due to it overriding the HOME envvar; I symlinked node_modules/electron-rebuild/lib/headers/.Multirust to ~/.multirust/

Edit2: And also .cargo - I see you already worked that out in the linked issue though.

**Comment by jedireza** [comment]
r+

I tested using the latest node 4, 6, 7 with mac and linux.

**Comment by dherman** [comment]
I'll follow up with the commits from @as-cii that eliminate the env var altogether.

**Pull request merged**
