### PR TITLE
Support npm scoped packages

### PR DESCRIPTION
**Pull request by watilde**
There is a [scoped package](https://docs.npmjs.com/misc/scope) in npm and `npm init` supported a scope option: https://docs.npmjs.com/cli/init#scope

I support the scope option in neon new by same way with npm like [this](https://github.com/npm/init-package-json/pull/31).

e.g.

```
$ neon new my-project --scope=@me
This utility will walk you through creating a Neon project.
It only covers the most common items, and tries to guess sensible defaults.

Press ^C at any time to quit.
? name @me/my-project
...follow prompts...

$ cat my-project/package.json
{
  "name": "@me/my-project",
  "version": "0.1.0",
  "description": "An example for #11 on dherman/neon-cli",
  "main": "lib/index.js",
  "scripts": {
    "postinstall": "neon build"
  },
  "author": "Daijiro Wachi <daijiro.wachi@gmail.com>",
  "license": "MIT",
  "dependencies": {
    "neon-cli": "^0.1.1",
    "neon-bridge": "^0.1.2"
  }
}
```

### CODE REVIEW

**Comment by dherman** [comment]
I'm afraid PR #9 caused conflicts for this one. Also, it'd be a nicer UX simply to allow `neon new @me/my-project` as the syntax, with the usage info saying:

```
neon new project
neon new @scope/project
```

I'd be happy to merge with that change.

**Comment by watilde** [comment]
Thanks for your comment Dave! I agreed the syntax and it has already supported. Then I updated my commit and it just became very tiny xD.

**Comment by watilde** [comment]
Notes

```
​[1:15] Cargo.toml should be just the part after the /
​[1:15] README.md could be the full scoped name
​[1:15] binding.cc should be just the part after the /
​[1:15] binding.gyp should be just the part after the /
​[1:16] package.json should be the full scoped name
```

**Comment by dherman** [comment]
I went ahead and implemented this in afcc283f3b7e5ee9c54b1e2fba8b4c9f683487d9 tonight because I needed to fix the name-managing logic and the CLI workflow a little bit. Thanks for bringing up scoped package names -- I wasn't thinking carefully enough about them before.

**Comment by watilde** [comment]
Great works! I'll try to add a test for the scoped package :3

**Pull request closed without merging**
